<?php

/**
 * BaseProject
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $company_id
 * @property Company $Company
 * 
 * @method string  getName()       Returns the current record's "name" value
 * @method integer getCompanyId()  Returns the current record's "company_id" value
 * @method Company getCompany()    Returns the current record's "Company" value
 * @method Project setName()       Sets the current record's "name" value
 * @method Project setCompanyId()  Sets the current record's "company_id" value
 * @method Project setCompany()    Sets the current record's "Company" value
 * 
 * @package    sfSesame
 * @subpackage model
 * @author     Rober Martín H
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProject extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('project');
        $this->hasColumn('name', 'string', 150, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 150,
             ));
        $this->hasColumn('company_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Company', array(
             'local' => 'company_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}