# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/07-Databases

all:
  doctrine:
    class: sfDoctrineDatabase

dev:
  doctrine:
    param:
      dsn:      mysql:host=localhost;dbname=sfSesame
      username: usrsfsesame
      password: Zrs23nTCPP7BamWQ

test:
  doctrine:
    param:
      dsn:      mysql:host=localhost;dbname=test_sfSesame
      username: tstsfsesame
      password: Bv8eKYXHE6BvnhWu

prod:
  doctrine:
    param:
      dsn:      mysql:host=localhost;dbname=sfSesame
      username: usrsfsesame
      password: Zrs23nTCPP7BamWQ
